# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `OasRails::OasRailsController`.
# Please instead update this file by running `bin/tapioca dsl OasRails::OasRailsController`.


class OasRails::OasRailsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
