# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `oas_rails` gem.
# Please instead update this file by running `bin/tapioca gem oas_rails`.


# source://oas_rails//lib/oas_rails.rb#5
module OasRails
  class << self
    # source://oas_rails//lib/oas_rails.rb#65
    def build; end

    # source://oas_rails//lib/oas_rails.rb#78
    def config; end

    # Configurations for make the OasRails engine Work.
    #
    # @yield [config]
    #
    # source://oas_rails//lib/oas_rails.rb#73
    def configure; end

    # source://oas_rails//lib/oas_rails.rb#82
    def configure_yard!; end

    # source://railties/8.0.2/lib/rails/engine.rb#413
    def railtie_helpers_paths; end

    # source://railties/8.0.2/lib/rails/engine.rb#396
    def railtie_namespace; end

    # source://railties/8.0.2/lib/rails/engine.rb#417
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://railties/8.0.2/lib/rails/engine.rb#402
    def table_name_prefix; end

    # source://railties/8.0.2/lib/rails/engine.rb#409
    def use_relative_model_naming?; end
  end
end

class OasRails::ApplicationController < ::ActionController::Base
  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  def _layout_from_proc; end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end

module OasRails::ApplicationController::HelperMethods
  include ::ActionText::ContentHelper
  include ::ActionText::TagHelper
  include ::Importmap::ImportmapTagsHelper
  include ::Turbo::DriveHelper
  include ::Turbo::FramesHelper
  include ::Turbo::IncludesHelper
  include ::Turbo::StreamsHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper
  include ::ActionController::Base::HelperMethods
  include ::OasRails::ApplicationHelper
end

module OasRails::ApplicationHelper; end
class OasRails::ApplicationJob < ::ActiveJob::Base; end

class OasRails::ApplicationMailer < ::ActionMailer::Base
  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__layout; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__layout=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__layout_conditions; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__layout_conditions=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_default_params; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_default_params=(new_value); end
  end
end

class OasRails::ApplicationRecord < ::ActiveRecord::Base
  include ::OasRails::ApplicationRecord::GeneratedAttributeMethods
  include ::OasRails::ApplicationRecord::GeneratedAssociationMethods

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__validators; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__validators=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_defined_enums; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_defined_enums=(new_value); end
  end
end

module OasRails::ApplicationRecord::GeneratedAssociationMethods; end
module OasRails::ApplicationRecord::GeneratedAttributeMethods; end

# source://oas_rails//lib/oas_rails.rb#14
module OasRails::Builders; end

# source://oas_rails//lib/oas_rails/builders/content_builder.rb#3
class OasRails::Builders::ContentBuilder
  # @return [ContentBuilder] a new instance of ContentBuilder
  #
  # source://oas_rails//lib/oas_rails/builders/content_builder.rb#4
  def initialize(specification, context); end

  # source://oas_rails//lib/oas_rails/builders/content_builder.rb#48
  def build; end

  # source://oas_rails//lib/oas_rails/builders/content_builder.rb#35
  def from_model_class(klass); end

  # source://oas_rails//lib/oas_rails/builders/content_builder.rb#16
  def with_examples(examples); end

  # source://oas_rails//lib/oas_rails/builders/content_builder.rb#22
  def with_examples_from_tags(tags); end

  # source://oas_rails//lib/oas_rails/builders/content_builder.rb#10
  def with_schema(schema); end
end

# source://oas_rails//lib/oas_rails/builders/esquema_builder.rb#3
module OasRails::Builders::EsquemaBuilder
  class << self
    # Builds a schema for a class when it is used as incoming API data.
    #
    # @param klass [Class] The class for which the schema is built.
    # @return [Hash] The schema as a JSON-compatible hash.
    #
    # source://oas_rails//lib/oas_rails/builders/esquema_builder.rb#9
    def build_incoming_schema(klass:, model_to_schema_class: T.unsafe(nil)); end

    # Builds a schema for a class when it is used as outgoing API data.
    #
    # @param klass [Class] The class for which the schema is built.
    # @return [Hash] The schema as a JSON-compatible hash.
    #
    # source://oas_rails//lib/oas_rails/builders/esquema_builder.rb#22
    def build_outgoing_schema(klass:, model_to_schema_class: T.unsafe(nil)); end

    private

    # Builds a schema with the given configuration.
    #
    # @param klass [Class] The class for which the schema is built.
    # @param model_to_schema_class [Class] The schema builder class.
    # @param excluded_columns [Array] Columns to exclude from the schema.
    # @param exclude_primary_key [Boolean] Whether to exclude the primary key.
    # @return [Hash] The schema as a JSON-compatible hash.
    #
    # source://oas_rails//lib/oas_rails/builders/esquema_builder.rb#40
    def build_schema(klass:, model_to_schema_class:, excluded_columns:, exclude_primary_key:); end

    # Configures common settings for schema building.
    #
    # Excludes associations and foreign keys from the schema.
    #
    # source://oas_rails//lib/oas_rails/builders/esquema_builder.rb#52
    def configure_common_settings(model_to_schema_class: T.unsafe(nil)); end
  end
end

# source://oas_rails//lib/oas_rails/builders/operation_builder.rb#3
class OasRails::Builders::OperationBuilder
  include ::OasRails::Extractors::OasRouteExtractor

  # @return [OperationBuilder] a new instance of OperationBuilder
  #
  # source://oas_rails//lib/oas_rails/builders/operation_builder.rb#6
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/builders/operation_builder.rb#27
  def build; end

  # source://oas_rails//lib/oas_rails/builders/operation_builder.rb#11
  def from_oas_route(oas_route); end
end

# source://oas_rails//lib/oas_rails/builders/parameter_builder.rb#3
class OasRails::Builders::ParameterBuilder
  # @return [ParameterBuilder] a new instance of ParameterBuilder
  #
  # source://oas_rails//lib/oas_rails/builders/parameter_builder.rb#4
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/builders/parameter_builder.rb#23
  def build; end

  # source://oas_rails//lib/oas_rails/builders/parameter_builder.rb#17
  def extract_word_before(string, param); end

  # source://oas_rails//lib/oas_rails/builders/parameter_builder.rb#9
  def from_path(path, param); end
end

# source://oas_rails//lib/oas_rails/builders/parameters_builder.rb#3
class OasRails::Builders::ParametersBuilder
  # @return [ParametersBuilder] a new instance of ParametersBuilder
  #
  # source://oas_rails//lib/oas_rails/builders/parameters_builder.rb#4
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/builders/parameters_builder.rb#32
  def build; end

  # source://oas_rails//lib/oas_rails/builders/parameters_builder.rb#9
  def from_oas_route(oas_route); end

  # source://oas_rails//lib/oas_rails/builders/parameters_builder.rb#18
  def parameters_from_tags(tags:); end
end

# source://oas_rails//lib/oas_rails/builders/path_item_builder.rb#3
class OasRails::Builders::PathItemBuilder
  # @return [PathItemBuilder] a new instance of PathItemBuilder
  #
  # source://oas_rails//lib/oas_rails/builders/path_item_builder.rb#4
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/builders/path_item_builder.rb#19
  def build; end

  # source://oas_rails//lib/oas_rails/builders/path_item_builder.rb#9
  def from_path(path, route_extractor: T.unsafe(nil)); end
end

# source://oas_rails//lib/oas_rails/builders/request_body_builder.rb#3
class OasRails::Builders::RequestBodyBuilder
  # @return [RequestBodyBuilder] a new instance of RequestBodyBuilder
  #
  # source://oas_rails//lib/oas_rails/builders/request_body_builder.rb#4
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/builders/request_body_builder.rb#40
  def build; end

  # source://oas_rails//lib/oas_rails/builders/request_body_builder.rb#32
  def from_model_class(klass:, **kwargs); end

  # source://oas_rails//lib/oas_rails/builders/request_body_builder.rb#9
  def from_oas_route(oas_route); end

  # source://oas_rails//lib/oas_rails/builders/request_body_builder.rb#20
  def from_tags(tag:, examples_tags: T.unsafe(nil)); end

  # source://oas_rails//lib/oas_rails/builders/request_body_builder.rb#46
  def reference; end

  private

  # source://oas_rails//lib/oas_rails/builders/request_body_builder.rb#54
  def detect_request_body(oas_route); end
end

# source://oas_rails//lib/oas_rails/builders/response_builder.rb#3
class OasRails::Builders::ResponseBuilder
  # @return [ResponseBuilder] a new instance of ResponseBuilder
  #
  # source://oas_rails//lib/oas_rails/builders/response_builder.rb#4
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/builders/response_builder.rb#35
  def build; end

  # source://oas_rails//lib/oas_rails/builders/response_builder.rb#27
  def from_tag(tag); end

  # source://oas_rails//lib/oas_rails/builders/response_builder.rb#21
  def with_code(code); end

  # source://oas_rails//lib/oas_rails/builders/response_builder.rb#15
  def with_content(content); end

  # source://oas_rails//lib/oas_rails/builders/response_builder.rb#9
  def with_description(description); end
end

# source://oas_rails//lib/oas_rails/builders/responses_builder.rb#3
class OasRails::Builders::ResponsesBuilder
  # @return [ResponsesBuilder] a new instance of ResponsesBuilder
  #
  # source://oas_rails//lib/oas_rails/builders/responses_builder.rb#4
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/builders/responses_builder.rb#20
  def add_autodiscovered_responses(oas_route); end

  # source://oas_rails//lib/oas_rails/builders/responses_builder.rb#32
  def add_default_responses(oas_route, security); end

  # source://oas_rails//lib/oas_rails/builders/responses_builder.rb#41
  def build; end

  # source://oas_rails//lib/oas_rails/builders/responses_builder.rb#9
  def from_oas_route(oas_route); end

  private

  # source://oas_rails//lib/oas_rails/builders/responses_builder.rb#63
  def add_responses_for_errors(errors); end

  # source://oas_rails//lib/oas_rails/builders/responses_builder.rb#47
  def determine_common_errors(oas_route, security); end

  # source://oas_rails//lib/oas_rails/builders/responses_builder.rb#74
  def resolve_response_body(error); end
end

# source://oas_rails//lib/oas_rails/configuration.rb#2
class OasRails::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#20
  def initialize; end

  # Returns the value of attribute api_path.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def api_path; end

  # Sets the attribute api_path
  #
  # @param value the value to set the attribute api_path to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def api_path=(_arg0); end

  # Returns the value of attribute authenticate_all_routes_by_default.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def authenticate_all_routes_by_default; end

  # Sets the attribute authenticate_all_routes_by_default
  #
  # @param value the value to set the attribute authenticate_all_routes_by_default to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def authenticate_all_routes_by_default=(_arg0); end

  # Returns the value of attribute autodiscover_request_body.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def autodiscover_request_body; end

  # Sets the attribute autodiscover_request_body
  #
  # @param value the value to set the attribute autodiscover_request_body to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def autodiscover_request_body=(_arg0); end

  # Returns the value of attribute autodiscover_responses.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def autodiscover_responses; end

  # Sets the attribute autodiscover_responses
  #
  # @param value the value to set the attribute autodiscover_responses to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def autodiscover_responses=(_arg0); end

  # source://oas_rails//lib/oas_rails/configuration.rb#65
  def default_servers; end

  # Returns the value of attribute default_tags_from.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def default_tags_from; end

  # Sets the attribute default_tags_from
  #
  # @param value the value to set the attribute default_tags_from to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def default_tags_from=(_arg0); end

  # source://oas_rails//lib/oas_rails/configuration.rb#77
  def excluded_columns_incoming; end

  # source://oas_rails//lib/oas_rails/configuration.rb#81
  def excluded_columns_outgoing; end

  # Returns the value of attribute http_verbs.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def http_verbs; end

  # Sets the attribute http_verbs
  #
  # @param value the value to set the attribute http_verbs to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def http_verbs=(_arg0); end

  # Returns the value of attribute ignored_actions.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def ignored_actions; end

  # Sets the attribute ignored_actions
  #
  # @param value the value to set the attribute ignored_actions to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def ignored_actions=(_arg0); end

  # Returns the value of attribute include_mode.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#18
  def include_mode; end

  # @raise [ArgumentError]
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#85
  def include_mode=(value); end

  # Returns the value of attribute info.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def info; end

  # Sets the attribute info
  #
  # @param value the value to set the attribute info to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def info=(_arg0); end

  # Returns the value of attribute layout.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def layout; end

  # Sets the attribute layout
  #
  # @param value the value to set the attribute layout to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def layout=(_arg0); end

  # Returns the value of attribute possible_default_responses.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def possible_default_responses; end

  # Sets the attribute possible_default_responses
  #
  # @param value the value to set the attribute possible_default_responses to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def possible_default_responses=(_arg0); end

  # Returns the value of attribute rapidoc_theme.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def rapidoc_theme; end

  # Sets the attribute rapidoc_theme
  #
  # @param value the value to set the attribute rapidoc_theme to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def rapidoc_theme=(_arg0); end

  # Returns the value of attribute response_body_of_default.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#18
  def response_body_of_default; end

  # @raise [ArgumentError]
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#92
  def response_body_of_default=(value); end

  # Returns the value of attribute security_schema.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#18
  def security_schema; end

  # source://oas_rails//lib/oas_rails/configuration.rb#59
  def security_schema=(value); end

  # Returns the value of attribute security_schemas.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def security_schemas; end

  # Sets the attribute security_schemas
  #
  # @param value the value to set the attribute security_schemas to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def security_schemas=(_arg0); end

  # Returns the value of attribute servers.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#18
  def servers; end

  # source://oas_rails//lib/oas_rails/configuration.rb#69
  def servers=(value); end

  # Returns the value of attribute set_default_responses.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def set_default_responses; end

  # Sets the attribute set_default_responses
  #
  # @param value the value to set the attribute set_default_responses to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def set_default_responses=(_arg0); end

  # Returns the value of attribute tags.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#18
  def tags; end

  # source://oas_rails//lib/oas_rails/configuration.rb#73
  def tags=(value); end

  # Returns the value of attribute use_model_names.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def use_model_names; end

  # Sets the attribute use_model_names
  #
  # @param value the value to set the attribute use_model_names to.
  #
  # source://oas_rails//lib/oas_rails/configuration.rb#3
  def use_model_names=(_arg0); end
end

# source://oas_rails//lib/oas_rails/configuration.rb#100
OasRails::DEFAULT_SECURITY_SCHEMES = T.let(T.unsafe(nil), Hash)

# source://oas_rails//lib/oas_rails/engine.rb#2
class OasRails::Engine < ::Rails::Engine
  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

# source://oas_rails//lib/oas_rails.rb#58
module OasRails::Extractors; end

# source://oas_rails//lib/oas_rails/extractors/oas_route_extractor.rb#3
module OasRails::Extractors::OasRouteExtractor
  # source://oas_rails//lib/oas_rails/extractors/oas_route_extractor.rb#21
  def default_tags(oas_route:); end

  # source://oas_rails//lib/oas_rails/extractors/oas_route_extractor.rb#8
  def extract_operation_id(oas_route:); end

  # source://oas_rails//lib/oas_rails/extractors/oas_route_extractor.rb#32
  def extract_security(oas_route:); end

  # source://oas_rails//lib/oas_rails/extractors/oas_route_extractor.rb#4
  def extract_summary(oas_route:); end

  # source://oas_rails//lib/oas_rails/extractors/oas_route_extractor.rb#12
  def extract_tags(oas_route:); end

  private

  # source://oas_rails//lib/oas_rails/extractors/oas_route_extractor.rb#48
  def generate_crud_name(method, controller); end
end

# Extracts and processes render responses from a given source.
#
# source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#4
module OasRails::Extractors::RenderResponseExtractor
  class << self
    # Extracts responses from the provided source string.
    #
    # @param source [String] The source string containing render calls.
    # @return [Array<Response>] An array of Response objects extracted from the source.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#10
    def extract_responses_from_source(specification, source:); end

    private

    # Builds schema and examples for array models.
    #
    # @param maybe_a_model [String] The model name or variable.
    # @param klass [Class] The class associated with the model.
    # @param schema [Hash] The schema for the model.
    # @return [Array<Hash, Hash>] An array where the first element is the schema and the second is the examples.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#112
    def build_array_model_schema_and_examples(maybe_a_model, klass, schema); end

    # Builds schema and examples based on the content type.
    #
    # @param content [String] The content extracted from the render call.
    # @return [Array<Hash, Hash>] An array where the first element is the schema and the second is the examples.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#44
    def build_schema_and_examples(content); end

    # Builds schema and examples for singular models.
    #
    # @param maybe_a_model [String] The model name or variable.
    # @param errors [String, nil] Errors related to the model.
    # @param klass [Class] The class associated with the model.
    # @param schema [Hash] The schema for the model.
    # @return [Array<Hash, Hash>] An array where the first element is the schema and the second is the examples.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#82
    def build_singular_model_schema_and_examples(_maybe_a_model, errors, klass, schema); end

    # Extracts render calls from the source string.
    #
    # @param source [String] The source string containing render calls.
    # @return [Array<Array<String, String>>] An array of arrays, each containing render content and status.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#23
    def extract_render_calls(source); end

    # Parses a hash literal to determine its structure.
    #
    # @param hash_literal [String] The hash literal string.
    # @return [Hash<Symbol, String>] A hash representing the structure of the input.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#129
    def parse_hash_structure(hash_literal); end

    # Processes non-hash content (e.g., model or method calls) to build schema and examples.
    #
    # @param content [String] The content extracted from the render call.
    # @return [Array<Hash, Hash>] An array where the first element is the schema and the second is the examples.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#59
    def process_non_hash_content(content); end

    # Processes the render content and status to build a Response object.
    #
    # @param content [String] The content extracted from the render call.
    # @param status [String] The status code associated with the render call.
    # @return [Response] A Response object based on the processed content and status.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#32
    def process_render_content(specification, content, status); end

    # Determines if a string represents a singular model.
    #
    # @param str [String] The string to test.
    # @return [Boolean] True if the string is a singular model, false otherwise.
    #
    # source://oas_rails//lib/oas_rails/extractors/render_response_extractor.rb#121
    def test_singularity(str); end
  end
end

# source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#3
class OasRails::Extractors::RouteExtractor
  class << self
    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#44
    def clean_route(route); end

    # Clear Class Instance Variable @host_routes
    #
    # This method clear the class instance variable @host_routes
    # to force a extraction of the routes again.
    #
    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#36
    def clear_cache; end

    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#40
    def host_paths; end

    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#28
    def host_routes; end

    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#23
    def host_routes_by_path(path); end

    private

    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#50
    def extract_host_routes; end

    # Ignore user-specified paths in initializer configuration.
    # Sanitize api_path by removing the "/" if it starts with that, and adding "/" if it ends without that.
    # Support controller name only to ignore all controller actions.
    # Support ignoring "controller#action"
    # Ignoring "controller#action" AND "api_path/controller#action"
    #
    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#102
    def ignore_custom_actions(route); end

    # @return [Boolean]
    #
    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#64
    def valid_api_route?(route); end

    # Checks if a route has a valid implementation.
    #
    # This method verifies that both the controller and the action specified
    # in the route exist. It checks if the controller class is defined and
    # if the action method is implemented within that controller.
    #
    # @param route [ActionDispatch::Journey::Route] The route to check.
    # @return [Boolean] true if both the controller and action exist, false otherwise.
    #
    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#82
    def valid_route_implementation?(route); end

    # source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#58
    def valid_routes; end
  end
end

# source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#4
OasRails::Extractors::RouteExtractor::RAILS_DEFAULT_CONTROLLERS = T.let(T.unsafe(nil), Array)

# source://oas_rails//lib/oas_rails/extractors/route_extractor.rb#18
OasRails::Extractors::RouteExtractor::RAILS_DEFAULT_PATHS = T.let(T.unsafe(nil), Array)

# The JsonSchemaGenerator module provides methods to transform string representations
# of data types into JSON schema formats.
#
# source://oas_rails//lib/oas_rails/json_schema_generator.rb#6
module OasRails::JsonSchemaGenerator
  class << self
    # Parses the properties of an object type from a string.
    #
    # @param str [String] The string representation of the object's properties.
    # @return [Hash] A hash where keys are property names and values are their JSON schema types.
    #
    # source://oas_rails//lib/oas_rails/json_schema_generator.rb#43
    def parse_object_properties(str); end

    # Parses a string representing a data type and determines its JSON schema type.
    #
    # @param str [String] The string representation of a data type.
    # @return [Hash] A hash containing the type, whether it's required, and any additional properties.
    #
    # source://oas_rails//lib/oas_rails/json_schema_generator.rb#23
    def parse_type(str); end

    # Processes a string representing a data type and converts it into a JSON schema.
    #
    # @param str [String] The string representation of a data type.
    # @return [Hash] A hash containing the required flag and the JSON schema.
    #
    # source://oas_rails//lib/oas_rails/json_schema_generator.rb#11
    def process_string(str); end

    # Converts a Ruby data type into its corresponding JSON schema type.
    #
    # @param type [Symbol, String] The Ruby data type.
    # @return [Hash, String] The JSON schema type or a hash with additional format information.
    #
    # source://oas_rails//lib/oas_rails/json_schema_generator.rb#116
    def ruby_type_to_json_schema_type(type); end

    # Converts a parsed data type into a JSON schema format.
    #
    # @param parsed [Hash] The parsed data type hash.
    # @return [Hash] The JSON schema representation of the parsed data type.
    #
    # source://oas_rails//lib/oas_rails/json_schema_generator.rb#86
    def to_json_schema(parsed); end
  end
end

class OasRails::OasRailsController < ::OasRails::ApplicationController
  def index; end

  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  def _layout_from_proc; end

  class << self
    # source://actionpack/8.0.2/lib/action_dispatch/routing/route_set.rb#612
    def _routes; end

    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end

module OasRails::OasRailsController::HelperMethods
  include ::ActionText::ContentHelper
  include ::ActionText::TagHelper
  include ::Importmap::ImportmapTagsHelper
  include ::Turbo::DriveHelper
  include ::Turbo::FramesHelper
  include ::Turbo::IncludesHelper
  include ::Turbo::StreamsHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::Turbo::Streams::ActionHelper
  include ::ActionController::Base::HelperMethods
  include ::OasRails::ApplicationHelper
  include ::OasRails::ApplicationController::HelperMethods
  include ::OasRails::OasRailsHelper
end

module OasRails::OasRailsHelper; end

# source://oas_rails//lib/oas_rails/oas_route.rb#2
class OasRails::OasRoute
  # @return [OasRoute] a new instance of OasRoute
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#6
  def initialize; end

  # Returns the value of attribute controller.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def controller; end

  # Sets the attribute controller
  #
  # @param value the value to set the attribute controller to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def controller=(_arg0); end

  # Returns the value of attribute controller_action.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def controller_action; end

  # Sets the attribute controller_action
  #
  # @param value the value to set the attribute controller_action to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def controller_action=(_arg0); end

  # Returns the value of attribute controller_class.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def controller_class; end

  # Sets the attribute controller_class
  #
  # @param value the value to set the attribute controller_class to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def controller_class=(_arg0); end

  # Returns the value of attribute controller_path.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def controller_path; end

  # Sets the attribute controller_path
  #
  # @param value the value to set the attribute controller_path to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def controller_path=(_arg0); end

  # source://oas_rails//lib/oas_rails/oas_route.rb#43
  def controller_path_extractor(controller); end

  # Returns the value of attribute docstring.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def docstring; end

  # Sets the attribute docstring
  #
  # @param value the value to set the attribute docstring to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def docstring=(_arg0); end

  # source://oas_rails//lib/oas_rails/oas_route.rb#27
  def extract_docstring; end

  # source://oas_rails//lib/oas_rails/oas_route.rb#15
  def extract_rails_route_data; end

  # source://oas_rails//lib/oas_rails/oas_route.rb#35
  def extract_source_string; end

  # Returns the value of attribute method.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def method; end

  # Sets the attribute method
  #
  # @param value the value to set the attribute method to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def method=(_arg0); end

  # Returns the value of attribute path.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def path; end

  # Sets the attribute path
  #
  # @param value the value to set the attribute path to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def path=(_arg0); end

  # source://oas_rails//lib/oas_rails/oas_route.rb#39
  def path_params; end

  # Returns the value of attribute rails_route.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def rails_route; end

  # Sets the attribute rails_route
  #
  # @param value the value to set the attribute rails_route to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def rails_route=(_arg0); end

  # Returns the value of attribute source_string.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def source_string; end

  # Sets the attribute source_string
  #
  # @param value the value to set the attribute source_string to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def source_string=(_arg0); end

  # Returns the value of attribute verb.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def verb; end

  # Sets the attribute verb
  #
  # @param value the value to set the attribute verb to.
  #
  # source://oas_rails//lib/oas_rails/oas_route.rb#3
  def verb=(_arg0); end

  class << self
    # source://oas_rails//lib/oas_rails/oas_route.rb#8
    def new_from_rails_route(rails_route: T.unsafe(nil)); end
  end
end

# This module contains all the clases that represent a part of the OAS file.
#
# source://oas_rails//lib/oas_rails.rb#27
module OasRails::Spec; end

# source://oas_rails//lib/oas_rails/spec/components.rb#3
class OasRails::Spec::Components
  include ::OasRails::Spec::Specable

  # @return [Components] a new instance of Components
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#8
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#64
  def add_example(example); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#32
  def add_parameter(parameter); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#39
  def add_request_body(request_body); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#25
  def add_response(response); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#46
  def add_schema(schema); end

  # Returns the value of attribute callbacks.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def callbacks; end

  # Sets the attribute callbacks
  #
  # @param value the value to set the attribute callbacks to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def callbacks=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#71
  def create_reference(type, name); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#87
  def example_reference(name); end

  # Returns the value of attribute examples.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def examples; end

  # Sets the attribute examples
  #
  # @param value the value to set the attribute examples to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def examples=(_arg0); end

  # Returns the value of attribute headers.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def headers; end

  # Sets the attribute headers
  #
  # @param value the value to set the attribute headers to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def headers=(_arg0); end

  # Returns the value of attribute links.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def links; end

  # Sets the attribute links
  #
  # @param value the value to set the attribute links to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def links=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#21
  def oas_fields; end

  # source://oas_rails//lib/oas_rails/spec/components.rb#83
  def parameter_reference(name); end

  # Returns the value of attribute parameters.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def parameters; end

  # Sets the attribute parameters
  #
  # @param value the value to set the attribute parameters to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def parameters=(_arg0); end

  # Returns the value of attribute request_bodies.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def request_bodies; end

  # Sets the attribute request_bodies
  #
  # @param value the value to set the attribute request_bodies to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def request_bodies=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#91
  def request_body_reference(name); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#79
  def response_reference(name); end

  # Returns the value of attribute responses.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def responses; end

  # Sets the attribute responses
  #
  # @param value the value to set the attribute responses to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def responses=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/components.rb#75
  def schema_reference(name); end

  # Returns the value of attribute schemas.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def schemas; end

  # Sets the attribute schemas
  #
  # @param value the value to set the attribute schemas to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def schemas=(_arg0); end

  # Returns the value of attribute security_schemes.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def security_schemes; end

  # Sets the attribute security_schemes
  #
  # @param value the value to set the attribute security_schemes to.
  #
  # source://oas_rails//lib/oas_rails/spec/components.rb#6
  def security_schemes=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/contact.rb#3
class OasRails::Spec::Contact
  include ::OasRails::Spec::Specable

  # @return [Contact] a new instance of Contact
  #
  # source://oas_rails//lib/oas_rails/spec/contact.rb#7
  def initialize(**kwargs); end

  # Returns the value of attribute email.
  #
  # source://oas_rails//lib/oas_rails/spec/contact.rb#5
  def email; end

  # Sets the attribute email
  #
  # @param value the value to set the attribute email to.
  #
  # source://oas_rails//lib/oas_rails/spec/contact.rb#5
  def email=(_arg0); end

  # Returns the value of attribute name.
  #
  # source://oas_rails//lib/oas_rails/spec/contact.rb#5
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # source://oas_rails//lib/oas_rails/spec/contact.rb#5
  def name=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/contact.rb#13
  def oas_fields; end

  # Returns the value of attribute url.
  #
  # source://oas_rails//lib/oas_rails/spec/contact.rb#5
  def url; end

  # Sets the attribute url
  #
  # @param value the value to set the attribute url to.
  #
  # source://oas_rails//lib/oas_rails/spec/contact.rb#5
  def url=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/hashable.rb#5
module OasRails::Spec::Hashable
  # source://oas_rails//lib/oas_rails/spec/hashable.rb#6
  def hash_key; end

  # source://oas_rails//lib/oas_rails/spec/hashable.rb#10
  def hash_representation; end

  # source://oas_rails//lib/oas_rails/spec/hashable.rb#18
  def public_instance_variables; end

  class << self
    # source://oas_rails//lib/oas_rails/spec/hashable.rb#14
    def generate_hash(obj); end

    # source://oas_rails//lib/oas_rails/spec/hashable.rb#25
    def hash_representation_recursive(obj); end
  end
end

# source://oas_rails//lib/oas_rails/spec/info.rb#3
class OasRails::Spec::Info
  include ::OasRails::Spec::Specable

  # @return [Info] a new instance of Info
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#7
  def initialize(**kwargs); end

  # Returns the value of attribute contact.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def contact; end

  # Sets the attribute contact
  #
  # @param value the value to set the attribute contact to.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def contact=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/info.rb#29
  def default_description; end

  # source://oas_rails//lib/oas_rails/spec/info.rb#25
  def default_summary; end

  # source://oas_rails//lib/oas_rails/spec/info.rb#21
  def default_title; end

  # Returns the value of attribute description.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def description=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def license; end

  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def license=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/info.rb#17
  def oas_fields; end

  # Returns the value of attribute summary.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def summary; end

  # Sets the attribute summary
  #
  # @param value the value to set the attribute summary to.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def summary=(_arg0); end

  # Returns the value of attribute terms_of_service.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def terms_of_service; end

  # Sets the attribute terms_of_service
  #
  # @param value the value to set the attribute terms_of_service to.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def terms_of_service=(_arg0); end

  # Returns the value of attribute title.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def title; end

  # Sets the attribute title
  #
  # @param value the value to set the attribute title to.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def title=(_arg0); end

  # Returns the value of attribute version.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def version; end

  # Sets the attribute version
  #
  # @param value the value to set the attribute version to.
  #
  # source://oas_rails//lib/oas_rails/spec/info.rb#5
  def version=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/license.rb#3
class OasRails::Spec::License
  include ::OasRails::Spec::Specable

  # @return [License] a new instance of License
  #
  # source://oas_rails//lib/oas_rails/spec/license.rb#8
  def initialize(**kwargs); end

  # Returns the value of attribute name.
  #
  # source://oas_rails//lib/oas_rails/spec/license.rb#6
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # source://oas_rails//lib/oas_rails/spec/license.rb#6
  def name=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/license.rb#13
  def oas_fields; end

  # Returns the value of attribute url.
  #
  # source://oas_rails//lib/oas_rails/spec/license.rb#6
  def url; end

  # Sets the attribute url
  #
  # @param value the value to set the attribute url to.
  #
  # source://oas_rails//lib/oas_rails/spec/license.rb#6
  def url=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/media_type.rb#3
class OasRails::Spec::MediaType
  include ::OasRails::Spec::Specable

  # Initializes a new MediaType object.
  #
  # @param schema [Hash] the schema of the media type.
  # @param kwargs [Hash] additional keyword arguments.
  # @return [MediaType] a new instance of MediaType
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#15
  def initialize(specification); end

  # Returns the value of attribute encoding.
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#6
  def encoding; end

  # Sets the attribute encoding
  #
  # @param value the value to set the attribute encoding to.
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#6
  def encoding=(_arg0); end

  # Returns the value of attribute example.
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#6
  def example; end

  # Sets the attribute example
  #
  # @param value the value to set the attribute example to.
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#6
  def example=(_arg0); end

  # Returns the value of attribute examples.
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#6
  def examples; end

  # Sets the attribute examples
  #
  # @param value the value to set the attribute examples to.
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#6
  def examples=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/media_type.rb#22
  def oas_fields; end

  # Returns the value of attribute schema.
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#6
  def schema; end

  # Sets the attribute schema
  #
  # @param value the value to set the attribute schema to.
  #
  # source://oas_rails//lib/oas_rails/spec/media_type.rb#6
  def schema=(_arg0); end

  class << self
    # Searches for examples in test files based on the provided class and test framework.
    #
    # @param klass [Class] the class to search examples for.
    # @param utils [Module] a utility module that provides the `detect_test_framework` method. Defaults to `Utils`.
    # @return [Hash] a hash containing examples data or an empty hash if no examples are found.
    #
    # source://oas_rails//lib/oas_rails/spec/media_type.rb#32
    def search_for_examples_in_tests(klass, context: T.unsafe(nil), utils: T.unsafe(nil)); end

    private

    # source://oas_rails//lib/oas_rails/spec/media_type.rb#83
    def clean_example_object(obj:); end

    # Fetches examples from FactoryBot for the provided class.
    #
    # @param klass [Class] the class to fetch examples for.
    # @return [Hash] a hash containing examples data or an empty hash if no examples are found.
    #
    # source://oas_rails//lib/oas_rails/spec/media_type.rb#50
    def fetch_factory_bot_examples(klass:); end

    # Fetches examples from fixtures for the provided class.
    #
    # @param klass [Class] the class to fetch examples for.
    # @return [Hash] a hash containing examples data or an empty hash if no examples are found.
    #
    # source://oas_rails//lib/oas_rails/spec/media_type.rb#68
    def fetch_fixture_examples(klass:); end
  end
end

# source://oas_rails//lib/oas_rails/spec/operation.rb#3
class OasRails::Spec::Operation
  include ::OasRails::Spec::Specable

  # @return [Operation] a new instance of Operation
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#8
  def initialize(specification); end

  # Returns the value of attribute description.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def description=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/operation.rb#20
  def oas_fields; end

  # Returns the value of attribute operation_id.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def operation_id; end

  # Sets the attribute operation_id
  #
  # @param value the value to set the attribute operation_id to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def operation_id=(_arg0); end

  # Returns the value of attribute parameters.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def parameters; end

  # Sets the attribute parameters
  #
  # @param value the value to set the attribute parameters to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def parameters=(_arg0); end

  # Returns the value of attribute request_body.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def request_body; end

  # Sets the attribute request_body
  #
  # @param value the value to set the attribute request_body to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def request_body=(_arg0); end

  # Returns the value of attribute responses.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def responses; end

  # Sets the attribute responses
  #
  # @param value the value to set the attribute responses to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def responses=(_arg0); end

  # Returns the value of attribute security.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def security; end

  # Sets the attribute security
  #
  # @param value the value to set the attribute security to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def security=(_arg0); end

  # Returns the value of attribute specification.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def specification; end

  # Sets the attribute specification
  #
  # @param value the value to set the attribute specification to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def specification=(_arg0); end

  # Returns the value of attribute summary.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def summary; end

  # Sets the attribute summary
  #
  # @param value the value to set the attribute summary to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def summary=(_arg0); end

  # Returns the value of attribute tags.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def tags; end

  # Sets the attribute tags
  #
  # @param value the value to set the attribute tags to.
  #
  # source://oas_rails//lib/oas_rails/spec/operation.rb#6
  def tags=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/parameter.rb#3
class OasRails::Spec::Parameter
  include ::OasRails::Spec::Specable
  include ::OasRails::Spec::Hashable

  # @return [Parameter] a new instance of Parameter
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#12
  def initialize(specification); end

  # Returns the value of attribute description.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def description=(_arg0); end

  # Returns the value of attribute in.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#10
  def in; end

  # source://oas_rails//lib/oas_rails/spec/parameter.rb#22
  def in=(value); end

  # Returns the value of attribute name.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def name=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/parameter.rb#32
  def oas_fields; end

  # Returns the value of attribute required.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def required; end

  # Sets the attribute required
  #
  # @param value the value to set the attribute required to.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def required=(_arg0); end

  # @return [Boolean]
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#28
  def required?; end

  # Returns the value of attribute schema.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def schema; end

  # Sets the attribute schema
  #
  # @param value the value to set the attribute schema to.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def schema=(_arg0); end

  # Returns the value of attribute style.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def style; end

  # Sets the attribute style
  #
  # @param value the value to set the attribute style to.
  #
  # source://oas_rails//lib/oas_rails/spec/parameter.rb#9
  def style=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/parameter.rb#7
OasRails::Spec::Parameter::STYLE_DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://oas_rails//lib/oas_rails/spec/path_item.rb#3
class OasRails::Spec::PathItem
  include ::OasRails::Spec::Specable

  # @return [PathItem] a new instance of PathItem
  #
  # source://oas_rails//lib/oas_rails/spec/path_item.rb#7
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/spec/path_item.rb#24
  def add_operation(http_method, operation); end

  # Returns the value of attribute delete.
  #
  # source://oas_rails//lib/oas_rails/spec/path_item.rb#5
  def delete; end

  # source://oas_rails//lib/oas_rails/spec/path_item.rb#16
  def fill_from(path, route_extractor: T.unsafe(nil)); end

  # Returns the value of attribute get.
  #
  # source://oas_rails//lib/oas_rails/spec/path_item.rb#5
  def get; end

  # source://oas_rails//lib/oas_rails/spec/path_item.rb#28
  def oas_fields; end

  # Returns the value of attribute patch.
  #
  # source://oas_rails//lib/oas_rails/spec/path_item.rb#5
  def patch; end

  # Returns the value of attribute post.
  #
  # source://oas_rails//lib/oas_rails/spec/path_item.rb#5
  def post; end

  # Returns the value of attribute put.
  #
  # source://oas_rails//lib/oas_rails/spec/path_item.rb#5
  def put; end
end

# source://oas_rails//lib/oas_rails/spec/paths.rb#3
class OasRails::Spec::Paths
  include ::OasRails::Spec::Specable

  # @return [Paths] a new instance of Paths
  #
  # source://oas_rails//lib/oas_rails/spec/paths.rb#8
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/spec/paths.rb#13
  def add_path(path); end

  # Returns the value of attribute path_items.
  #
  # source://oas_rails//lib/oas_rails/spec/paths.rb#6
  def path_items; end

  # Sets the attribute path_items
  #
  # @param value the value to set the attribute path_items to.
  #
  # source://oas_rails//lib/oas_rails/spec/paths.rb#6
  def path_items=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/paths.rb#17
  def to_spec; end
end

# source://oas_rails//lib/oas_rails/spec/reference.rb#3
class OasRails::Spec::Reference
  include ::OasRails::Spec::Specable

  # @return [Reference] a new instance of Reference
  #
  # source://oas_rails//lib/oas_rails/spec/reference.rb#7
  def initialize(ref); end

  # Returns the value of attribute ref.
  #
  # source://oas_rails//lib/oas_rails/spec/reference.rb#5
  def ref; end

  # source://oas_rails//lib/oas_rails/spec/reference.rb#11
  def to_spec; end
end

# source://oas_rails//lib/oas_rails/spec/request_body.rb#3
class OasRails::Spec::RequestBody
  include ::OasRails::Spec::Specable
  include ::OasRails::Spec::Hashable

  # @return [RequestBody] a new instance of RequestBody
  #
  # source://oas_rails//lib/oas_rails/spec/request_body.rb#9
  def initialize(specification); end

  # Returns the value of attribute content.
  #
  # source://oas_rails//lib/oas_rails/spec/request_body.rb#7
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://oas_rails//lib/oas_rails/spec/request_body.rb#7
  def content=(_arg0); end

  # Returns the value of attribute description.
  #
  # source://oas_rails//lib/oas_rails/spec/request_body.rb#7
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # source://oas_rails//lib/oas_rails/spec/request_body.rb#7
  def description=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/request_body.rb#16
  def oas_fields; end

  # Returns the value of attribute required.
  #
  # source://oas_rails//lib/oas_rails/spec/request_body.rb#7
  def required; end

  # Sets the attribute required
  #
  # @param value the value to set the attribute required to.
  #
  # source://oas_rails//lib/oas_rails/spec/request_body.rb#7
  def required=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/response.rb#3
class OasRails::Spec::Response
  include ::OasRails::Spec::Specable
  include ::OasRails::Spec::Hashable

  # @return [Response] a new instance of Response
  #
  # source://oas_rails//lib/oas_rails/spec/response.rb#9
  def initialize(specification); end

  # Returns the value of attribute code.
  #
  # source://oas_rails//lib/oas_rails/spec/response.rb#7
  def code; end

  # Sets the attribute code
  #
  # @param value the value to set the attribute code to.
  #
  # source://oas_rails//lib/oas_rails/spec/response.rb#7
  def code=(_arg0); end

  # Returns the value of attribute content.
  #
  # source://oas_rails//lib/oas_rails/spec/response.rb#7
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://oas_rails//lib/oas_rails/spec/response.rb#7
  def content=(_arg0); end

  # Returns the value of attribute description.
  #
  # source://oas_rails//lib/oas_rails/spec/response.rb#7
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # source://oas_rails//lib/oas_rails/spec/response.rb#7
  def description=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/response.rb#15
  def oas_fields; end
end

# source://oas_rails//lib/oas_rails/spec/responses.rb#3
class OasRails::Spec::Responses
  include ::OasRails::Spec::Specable

  # @return [Responses] a new instance of Responses
  #
  # source://oas_rails//lib/oas_rails/spec/responses.rb#7
  def initialize(specification); end

  # source://oas_rails//lib/oas_rails/spec/responses.rb#12
  def add_response(response); end

  # Returns the value of attribute responses.
  #
  # source://oas_rails//lib/oas_rails/spec/responses.rb#5
  def responses; end

  # Sets the attribute responses
  #
  # @param value the value to set the attribute responses to.
  #
  # source://oas_rails//lib/oas_rails/spec/responses.rb#5
  def responses=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/responses.rb#16
  def to_spec; end
end

# source://oas_rails//lib/oas_rails/spec/server.rb#3
class OasRails::Spec::Server
  include ::OasRails::Spec::Specable

  # @return [Server] a new instance of Server
  #
  # source://oas_rails//lib/oas_rails/spec/server.rb#7
  def initialize(url:, description:); end

  # Returns the value of attribute description.
  #
  # source://oas_rails//lib/oas_rails/spec/server.rb#5
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # source://oas_rails//lib/oas_rails/spec/server.rb#5
  def description=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/server.rb#12
  def oas_fields; end

  # Returns the value of attribute url.
  #
  # source://oas_rails//lib/oas_rails/spec/server.rb#5
  def url; end

  # Sets the attribute url
  #
  # @param value the value to set the attribute url to.
  #
  # source://oas_rails//lib/oas_rails/spec/server.rb#5
  def url=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/specable.rb#3
module OasRails::Spec::Specable
  # source://oas_rails//lib/oas_rails/spec/specable.rb#36
  def as_json(options = T.unsafe(nil)); end

  # source://oas_rails//lib/oas_rails/spec/specable.rb#4
  def oas_fields; end

  # source://oas_rails//lib/oas_rails/spec/specable.rb#8
  def to_spec; end

  private

  # source://oas_rails//lib/oas_rails/spec/specable.rb#47
  def snake_to_camel(snake_str); end

  # @return [Boolean]
  #
  # source://oas_rails//lib/oas_rails/spec/specable.rb#43
  def valid_processed_value?(processed_value); end
end

# source://oas_rails//lib/oas_rails/spec/specification.rb#5
class OasRails::Spec::Specification
  include ::OasRails::Spec::Specable

  # Initializes a new Specification object.
  # Clears the cache if running in the development environment.
  #
  # @return [Specification] a new instance of Specification
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#11
  def initialize; end

  # source://oas_rails//lib/oas_rails/spec/specification.rb#23
  def build(route_extractor: T.unsafe(nil)); end

  # Clears the cache for MethodSource and RouteExtractor.
  #
  # @return [void]
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#32
  def clear_cache; end

  # Returns the value of attribute components.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def components; end

  # Sets the attribute components
  #
  # @param value the value to set the attribute components to.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def components=(_arg0); end

  # Returns the value of attribute external_docs.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def external_docs; end

  # Sets the attribute external_docs
  #
  # @param value the value to set the attribute external_docs to.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def external_docs=(_arg0); end

  # Returns the value of attribute info.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def info; end

  # Sets the attribute info
  #
  # @param value the value to set the attribute info to.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def info=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/specification.rb#37
  def oas_fields; end

  # Returns the value of attribute openapi.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def openapi; end

  # Sets the attribute openapi
  #
  # @param value the value to set the attribute openapi to.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def openapi=(_arg0); end

  # Returns the value of attribute paths.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def paths; end

  # Sets the attribute paths
  #
  # @param value the value to set the attribute paths to.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def paths=(_arg0); end

  # Create the Security Requirement Object.
  #
  # @see https://spec.openapis.org/oas/latest.html#security-requirement-object
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#43
  def security; end

  # Returns the value of attribute servers.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def servers; end

  # Sets the attribute servers
  #
  # @param value the value to set the attribute servers to.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def servers=(_arg0); end

  # Returns the value of attribute tags.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def tags; end

  # Sets the attribute tags
  #
  # @param value the value to set the attribute tags to.
  #
  # source://oas_rails//lib/oas_rails/spec/specification.rb#7
  def tags=(_arg0); end
end

# source://oas_rails//lib/oas_rails/spec/tag.rb#3
class OasRails::Spec::Tag
  include ::OasRails::Spec::Specable

  # @return [Tag] a new instance of Tag
  #
  # source://oas_rails//lib/oas_rails/spec/tag.rb#8
  def initialize(name:, description:); end

  # Returns the value of attribute description.
  #
  # source://oas_rails//lib/oas_rails/spec/tag.rb#6
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # source://oas_rails//lib/oas_rails/spec/tag.rb#6
  def description=(_arg0); end

  # Returns the value of attribute name.
  #
  # source://oas_rails//lib/oas_rails/spec/tag.rb#6
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # source://oas_rails//lib/oas_rails/spec/tag.rb#6
  def name=(_arg0); end

  # source://oas_rails//lib/oas_rails/spec/tag.rb#13
  def oas_fields; end
end

module OasRails::TestHelper; end

# source://oas_rails//lib/oas_rails/utils.rb#2
module OasRails::Utils
  class << self
    # Checks if a given text refers to an ActiveRecord class.
    #
    # @param text [String] The text to check.
    # @return [Boolean] True if the text refers to an ActiveRecord class, false otherwise.
    #
    # source://oas_rails//lib/oas_rails/utils.rb#112
    def active_record_class?(klass_or_string); end

    # source://oas_rails//lib/oas_rails/utils.rb#85
    def class_to_symbol(klass); end

    # Method for detect test framework of the Rails App
    # It is used for generate examples in operations
    #
    # source://oas_rails//lib/oas_rails/utils.rb#29
    def detect_test_framework; end

    # source://oas_rails//lib/oas_rails/utils.rb#89
    def find_model_from_route(path); end

    # Converts a status code to its corresponding text description.
    #
    # @param status_code [Integer] The status code.
    # @return [String] The text description of the status code.
    #
    # source://oas_rails//lib/oas_rails/utils.rb#81
    def get_definition(status_code); end

    # source://oas_rails//lib/oas_rails/utils.rb#39
    def hash_to_json_schema(hash); end

    # source://oas_rails//lib/oas_rails/utils.rb#47
    def hash_to_properties(hash); end

    # source://oas_rails//lib/oas_rails/utils.rb#59
    def ruby_type_to_json_type(ruby_type); end

    # Converts a status symbol or string to an integer.
    #
    # @param status [String, Symbol, nil] The status to convert.
    # @return [Integer] The status code as an integer.
    #
    # source://oas_rails//lib/oas_rails/utils.rb#67
    def status_to_integer(status); end
  end
end

# source://oas_rails//lib/oas_rails/utils.rb#16
OasRails::Utils::HTTP_STATUS_DEFINITIONS = T.let(T.unsafe(nil), Hash)

# source://oas_rails//lib/oas_rails/utils.rb#3
OasRails::Utils::TYPE_MAPPING = T.let(T.unsafe(nil), Hash)

# source://oas_rails//lib/oas_rails/version.rb#2
OasRails::VERSION = T.let(T.unsafe(nil), String)

# source://oas_rails//lib/oas_rails.rb#48
module OasRails::YARD; end

# source://oas_rails//lib/oas_rails/yard/example_tag.rb#3
class OasRails::YARD::ExampleTag < ::YARD::Tags::Tag
  # @return [ExampleTag] a new instance of ExampleTag
  #
  # source://oas_rails//lib/oas_rails/yard/example_tag.rb#6
  def initialize(tag_name, text, content: T.unsafe(nil)); end

  # Returns the value of attribute content.
  #
  # source://oas_rails//lib/oas_rails/yard/example_tag.rb#4
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://oas_rails//lib/oas_rails/yard/example_tag.rb#4
  def content=(_arg0); end
end

# source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#3
class OasRails::YARD::OasRailsFactory < ::YARD::Tags::DefaultFactory
  # Parses a tag that represents a parameter.
  #
  # @param tag_name [String] The name of the tag.
  # @param text [String] The tag text to parse.
  # @return [ParameterTag] The parsed parameter tag object.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#26
  def parse_tag_with_parameter(tag_name, text); end

  # Parses a tag that represents a request body.
  #
  # @param tag_name [String] The name of the tag.
  # @param text [String] The tag text to parse.
  # @return [RequestBodyTag] The parsed request body tag object.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#8
  def parse_tag_with_request_body(tag_name, text); end

  # Parses a tag that represents a request body example.
  #
  # @param tag_name [String] The name of the tag.
  # @param text [String] The tag text to parse.
  # @return [RequestBodyExampleTag] The parsed request body example tag object.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#17
  def parse_tag_with_request_body_example(tag_name, text); end

  # Parses a tag that represents a response.
  #
  # @param tag_name [String] The name of the tag.
  # @param text [String] The tag text to parse.
  # @return [ResponseTag] The parsed response tag object.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#36
  def parse_tag_with_response(tag_name, text); end

  # Parses a tag that represents a response example.
  #
  # @param tag_name [String] The name of the tag.
  # @param text [String] The tag text to parse.
  # @return [ResponseExampleTag] The parsed response example tag object.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#45
  def parse_tag_with_response_example(tag_name, text); end

  private

  # Matches and validates a description and type from text.
  #
  # @param text [String] The text to parse.
  # @raise [ArgumentError]
  # @return [MatchData] The match data from the regex.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#143
  def description_and_type(text); end

  # Evaluates a string as a hash, handling errors gracefully.
  #
  # @param content [String] The content string to evaluate.
  # @return [Hash] The evaluated hash, or an empty hash if an error occurs.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#111
  def eval_content(content); end

  # Specific method to extract description and schema for request body tags.
  #
  # @param text [String] The text to parse.
  # @return [Array] An array containing the description, class, schema, and required flag.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#70
  def extract_description_and_schema(text); end

  # Reusable method for extracting description, type, and content with an option to process content.
  #
  # @param text [String] The text to parse.
  # @param process_content [Boolean] Whether to evaluate the content as a hash.
  # @raise [ArgumentError]
  # @return [Array] An array containing the description, type, and content or remaining text.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#56
  def extract_description_type_and_content(text, process_content: T.unsafe(nil), expresion: T.unsafe(nil)); end

  # Specific method to extract name, code, and hash for responses examples.
  #
  # @param text [String] The text to parse.
  # @return [Array] An array containing the name, code, and schema.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#100
  def extract_name_code_and_hash(text); end

  # Specific method to extract name, code, and schema for responses.
  #
  # @param text [String] The text to parse.
  # @return [Array] An array containing the name, code, and schema.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#90
  def extract_name_code_and_schema(text); end

  # Specific method to extract name, location, and schema for parameters.
  #
  # @param text [String] The text to parse.
  # @return [Array] An array containing the name, location, schema, and required flag.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#79
  def extract_name_location_schema_and_description(text); end

  # Parses the position name and location from input text.
  #
  # @param input [String] The input text to parse.
  # @return [Array] An array containing the name and location.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#121
  def extract_text_and_parentheses_content(input); end

  # Extracts the text and whether it's required.
  #
  # @param text [String] The text to parse.
  # @return [Array] An array containing the text and a required flag.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#132
  def text_and_required(text); end

  # Converts type text to a schema, checking if it's an ActiveRecord class.
  #
  # @param text [String] The type text to convert.
  # @return [Array] An array containing the class, schema, and required flag.
  #
  # source://oas_rails//lib/oas_rails/yard/oas_rails_factory.rb#153
  def type_text_to_schema(text); end
end

# source://oas_rails//lib/oas_rails/yard/parameter_tag.rb#3
class OasRails::YARD::ParameterTag < ::YARD::Tags::Tag
  # @return [ParameterTag] a new instance of ParameterTag
  #
  # source://oas_rails//lib/oas_rails/yard/parameter_tag.rb#6
  def initialize(tag_name, name, text, schema, location, required: T.unsafe(nil)); end

  # Returns the value of attribute location.
  #
  # source://oas_rails//lib/oas_rails/yard/parameter_tag.rb#4
  def location; end

  # Sets the attribute location
  #
  # @param value the value to set the attribute location to.
  #
  # source://oas_rails//lib/oas_rails/yard/parameter_tag.rb#4
  def location=(_arg0); end

  # Returns the value of attribute required.
  #
  # source://oas_rails//lib/oas_rails/yard/parameter_tag.rb#4
  def required; end

  # Sets the attribute required
  #
  # @param value the value to set the attribute required to.
  #
  # source://oas_rails//lib/oas_rails/yard/parameter_tag.rb#4
  def required=(_arg0); end

  # Returns the value of attribute schema.
  #
  # source://oas_rails//lib/oas_rails/yard/parameter_tag.rb#4
  def schema; end

  # Sets the attribute schema
  #
  # @param value the value to set the attribute schema to.
  #
  # source://oas_rails//lib/oas_rails/yard/parameter_tag.rb#4
  def schema=(_arg0); end
end

# source://oas_rails//lib/oas_rails/yard/request_body_example_tag.rb#3
class OasRails::YARD::RequestBodyExampleTag < ::OasRails::YARD::ExampleTag
  # @return [RequestBodyExampleTag] a new instance of RequestBodyExampleTag
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_example_tag.rb#6
  def initialize(tag_name, text, content: T.unsafe(nil)); end

  # Returns the value of attribute content.
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_example_tag.rb#4
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_example_tag.rb#4
  def content=(_arg0); end
end

# source://oas_rails//lib/oas_rails/yard/request_body_tag.rb#3
class OasRails::YARD::RequestBodyTag < ::YARD::Tags::Tag
  # @return [RequestBodyTag] a new instance of RequestBodyTag
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_tag.rb#6
  def initialize(tag_name, text, klass, schema: T.unsafe(nil), required: T.unsafe(nil)); end

  # Returns the value of attribute klass.
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_tag.rb#4
  def klass; end

  # Sets the attribute klass
  #
  # @param value the value to set the attribute klass to.
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_tag.rb#4
  def klass=(_arg0); end

  # Returns the value of attribute required.
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_tag.rb#4
  def required; end

  # Sets the attribute required
  #
  # @param value the value to set the attribute required to.
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_tag.rb#4
  def required=(_arg0); end

  # Returns the value of attribute schema.
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_tag.rb#4
  def schema; end

  # Sets the attribute schema
  #
  # @param value the value to set the attribute schema to.
  #
  # source://oas_rails//lib/oas_rails/yard/request_body_tag.rb#4
  def schema=(_arg0); end
end

# source://oas_rails//lib/oas_rails/yard/response_example_tag.rb#3
class OasRails::YARD::ResponseExampleTag < ::OasRails::YARD::ExampleTag
  # @return [ResponseExampleTag] a new instance of ResponseExampleTag
  #
  # source://oas_rails//lib/oas_rails/yard/response_example_tag.rb#6
  def initialize(tag_name, text, content: T.unsafe(nil), code: T.unsafe(nil)); end

  # Returns the value of attribute code.
  #
  # source://oas_rails//lib/oas_rails/yard/response_example_tag.rb#4
  def code; end

  # Sets the attribute code
  #
  # @param value the value to set the attribute code to.
  #
  # source://oas_rails//lib/oas_rails/yard/response_example_tag.rb#4
  def code=(_arg0); end
end

# source://oas_rails//lib/oas_rails/yard/response_tag.rb#3
class OasRails::YARD::ResponseTag < ::YARD::Tags::Tag
  # TODO: name == code. The name MUST be changed to code for better understanding
  #
  # @return [ResponseTag] a new instance of ResponseTag
  #
  # source://oas_rails//lib/oas_rails/yard/response_tag.rb#7
  def initialize(tag_name, name, text, schema); end

  # Returns the value of attribute schema.
  #
  # source://oas_rails//lib/oas_rails/yard/response_tag.rb#4
  def schema; end

  # Sets the attribute schema
  #
  # @param value the value to set the attribute schema to.
  #
  # source://oas_rails//lib/oas_rails/yard/response_tag.rb#4
  def schema=(_arg0); end
end
